### ISSUE TITLE
fragment销毁binding时机错误

### ISSUE THREAD

**Issue by xwhPanda** [MReP1/LittleGooseOffice#2]
`thisRef.viewLifecycleOwner.lifecycle.addObserver(object : DefaultLifecycleObserver {
                override fun onDestroy(owner: LifecycleOwner) {
                    super.onDestroy(owner)
                    // Fragment.viewLifecycleOwner call LifecycleObserver.onDestroy() before Fragment.onDestroyView().
                    // That's why we need to postpone reset of the viewBinding
                    Handler(Looper.getMainLooper()).post { binding = null }
                    thisRef.viewLifecycleOwner.lifecycle.removeObserver(this)
                }
            })`
销毁binding是不是应该在onDestroyView方法
这句注释是不是也是错误的Fragment.viewLifecycleOwner call LifecycleObserver.onDestroy() before Fragment.onDestroyView().
onDestroyView应该是在onDestroy之前调用

**Comment by MReP1** [comment]
此处获取的是Fragment的viewLifecycleOwner来添加Observer，在Fragment中先调用viewLifecycleOwner的onDestroy，再调用Fragment的onDestroyView。具体可以查看Fragment源码的performDestroyView函数。

**Comment by xwhPanda** [comment]
> 此处获取的是Fragment的viewLifecycleOwner来添加Observer，在Fragment中先调用viewLifecycleOwner的onDestroy，再调用Fragment的onDestroyView。具体可以查看Fragment源码的performDestroyView函数。

看到viewLifecycleOwner了,受教了
